# Proyecto: Predicción de renuncia de clientes de un banco.

#Importando Dataset y Librerías

In [6]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [9]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [10]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [11]:
print(y)

[1 0 1 ... 1 1 0]


#Preprocesamiento de datos

##Codificando datos categóricos

Codificando etiqueta "género"



In [43]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [44]:
print(X)

[[1.0 0.0 1 ... 1 1 101348.88]
 [1.0 0.0 0 ... 0 1 112542.58]
 [1.0 0.0 1 ... 1 0 113931.57]
 ...
 [1.0 0.0 1 ... 0 1 42085.58]
 [0.0 1.0 0 ... 1 0 92888.52]
 [1.0 0.0 1 ... 1 0 38190.78]]


Codificando columna de zona geográfica.

In [45]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [46]:
print(X)

[[1.0 0.0 1.0 ... 1 1 101348.88]
 [1.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 1.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 1.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 1.0 ... 1 0 38190.78]]


##Dividir dataset en set de entrenamiento y set de testeo.

In [47]:
from sklearn.model_selection import train_test_split,KFold


X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 1)

In [48]:
print(X_train)

[[1.0 0.0 1.0 ... 1 0 163830.64]
 [0.0 1.0 0.0 ... 1 1 57098.0]
 [1.0 0.0 1.0 ... 1 0 185630.76]
 ...
 [1.0 0.0 1.0 ... 1 0 181429.87]
 [1.0 0.0 1.0 ... 1 1 148750.16]
 [0.0 1.0 0.0 ... 1 0 118855.26]]


In [49]:
print(X_test)

[[0.0 1.0 0.0 ... 1 1 192852.67]
 [1.0 0.0 1.0 ... 1 0 128702.1]
 [1.0 0.0 1.0 ... 1 1 75732.25]
 ...
 [1.0 0.0 1.0 ... 1 0 141533.19]
 [0.0 1.0 0.0 ... 1 1 11276.48]
 [0.0 1.0 0.0 ... 1 0 192950.6]]


In [50]:
print(y_train)

[0 0 0 ... 0 0 1]


In [51]:
print(y_test)

[0 1 0 ... 0 0 0]


Escalado de valores.

In [52]:
from sklearn.preprocessing import  StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#Creando la red neuronal.

Inicializando la red neuronal.

In [22]:
ann = tf.keras.models.Sequential()

Añadiendo la capa de entrada.

In [23]:
ann.add(tf.keras.layers.Dense(units=8,activation='relu'))

Añadiendo segunda capa oculta.

In [24]:
ann.add(tf.keras.layers.Dense(units=8,activation='relu'))

Añadiendo capa de salida.

In [25]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

#Entrenando la red neuronal.

Compilando la red neuronal.

In [26]:
ann.compile(optimizer = 'adam' , loss = 'binary_crossentropy', metrics = ['accuracy'])

Entrenando la red neuronal con el set de entrenamiento.

In [27]:
ann.fit(X_train,y_train, batch_size =  32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5389 - accuracy: 0.7598
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4550 - accuracy: 0.7970
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4399 - accuracy: 0.8018
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4317 - accuracy: 0.8069
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4254 - accuracy: 0.8127
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4204 - accuracy: 0.8194
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4162 - accuracy: 0.8234
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4120 - accuracy: 0.8246
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4084 - accuracy: 0.8281
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4054 - accura

#Realizando las predicciones y evaluando el modelo.

Predecir el resultado de una sola persona.

In [29]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])) > 0.5)

[[False]]


Precir los resultados del test set.

In [31]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Matriz de confusión.

In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1507   88]
 [ 197  208]]


0.8575